version: '2'
services:

  camunda:
    build:
      context: ./infra/camunda
      dockerfile: Dockerfile
    ports:
      - 80:8080

  camunda-gmail-worker:
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: ./infra/workers
      dockerfile: Dockerfile-Gmail-Worker
    depends_on:
      - gmail-credentials-offer
    volumes:
      - credentials:/app/credentials
    entrypoint: ["/usr/local/bin/python"]
    command: ["/app/CamundaGMAILWorker.py", "http://camunda:8080"]

  camunda-rf-worker:
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: ./infra/workers
      dockerfile: Dockerfile-RF-Worker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["/usr/local/bin/python"]
    command: ["/app/CamundaRFWorker.py", "http://camunda:8080"]

  ### JUST SINGLE EXECUTERS -> No infinity loop
  camunda-modeler-push:
    build:
      context: ./infra/camunda-model-push
      dockerfile: Dockerfile
    depends_on:
      - camunda
    volumes:
      - ./infra/camunda-model-push/model:/model
    entrypoint: /wait-for-it/wait-for-it.sh camunda:8080 -- /entrypoint.sh /model camunda:8080
    
  gmail-credentials-offer:
    build:
      context: ./infra/credential-mount-creator
      dockerfile: Dockerfile
    volumes:
      - ./infra/workers/credentials:/git/credentials
      - credentials:/credentials
    entrypoint: /entrypoint.sh /git/credentials/ /credentials

  robotframework:
    build:
      context: ./infra/robotframework
      dockerfile: Dockerfile
    entrypoint: ["tail", "/dev/null"]

volumes:
  credentials:
