version: '2'
services:

  camunda:
    build:
      context: ./infra/camunda
      dockerfile: Dockerfile
    ports:
      - 80:8080
    #volumes:
    #  - ./infra/camunda/config/camunda_initialise.sh:/docker-entrypoint.d/camunda_initialise.sh
    #environment:
    #  - GITREPO="https://github.com/TheProjectAurora/gocd-katas.git"

  camunda-modeler:
    build:
      context: ./infra/camunda-model-push
      dockerfile: Dockerfile
    depends_on:
      - camunda
    entrypoint: /wait-for-it/wait-for-it.sh camunda:8080 -- /usr/bin/curl -X POST -F "upload=@/model/camunda_rf_demo.bpmn" http://camunda:8080/engine-rest/deployment/create
    volumes:
      - ./infra/camunda-modeler/config/:/model/

  camunda-gmail-worker:
    build:
      context: ./infra/workers
      dockerfile: Dockerfile-Gmail-Worker
    entrypoint: ["/usr/local/bin/python"]
    command: ["/app/CamundaGMAILWorker.py", "http://camunda:8080"]

  camunda-rf-worker:
    build:
      context: ./infra/workers
      dockerfile: Dockerfile-RF-Worker
    entrypoint: ["/usr/local/bin/python"]
    command: ["/app/CamundaRFWorker.py", "http://camunda:8080"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  robotframework:
    build:
      context: ./infra/robotframework
      dockerfile: Dockerfile
    entrypoint: ["tail", "/dev/null"]