version: '2'
services:

  camunda:
    build:
      context: ./infra/camunda
      dockerfile: Dockerfile
    ports:
      - 80:8080


  camunda-modeler-push:
    build:
      context: ./infra/camunda-model-push
      dockerfile: Dockerfile
    depends_on:
      - camunda
    entrypoint: /wait-for-it/wait-for-it.sh camunda:8080 -- /entrypoint.sh /model camunda:8080
    volumes:
      - ./infra/camunda-model-push/model/:/model/

  camunda-gmail-worker:
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: ./infra/workers
      dockerfile: Dockerfile-Gmail-Worker
    entrypoint: ["/usr/local/bin/python"]
    command: ["/app/CamundaGMAILWorker.py", "http://camunda:8080"]
    volumes:
      - ./infra/workers/credentials/:/app/credentials/

  camunda-rf-worker:
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: ./infra/workers
      dockerfile: Dockerfile-RF-Worker
    entrypoint: ["/usr/local/bin/python"]
    command: ["/app/CamundaRFWorker.py", "http://camunda:8080"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./infra/workers/credentials/:/app/credentials/

  robotframework:
    build:
      context: ./infra/robotframework
      dockerfile: Dockerfile
    entrypoint: ["tail", "/dev/null"]