FROM python:3-alpine
COPY ./libraries /app/libraries
COPY ./camunda-gmail-worker/CamundaGMAILWorker.py /app
COPY ./camunda-gmail-worker/requirements.txt /tmp
RUN set -xe && \
    chmod +x /app/CamundaGMAILWorker.py && \
    pip3 install install -r /tmp/requirements.txt
