FROM python:3-alpine
COPY ./libraries /app/libraries
COPY ./camunda-rf-worker/requirements.txt /tmp/requirements.txt
COPY ./camunda-rf-worker/CamundaRFWorker.py /app/CamundaRFWorker.py
RUN set -xe && \
    chmod +x /app/CamundaRFWorker.py && \
    pip3 install install -r /tmp/requirements.txt