FROM python:3-alpine
COPY ./libraries /app/libraries
COPY ./camunda-rf-worker/requirements.txt /tmp
COPY ./camunda-rf-worker/CamundaRFWorker.py /app
RUN set -xe && \
    chmod +x /app/CamundaRFWorker.py && \
    pip3 install install -r /tmp/requirements.txt