FROM camunda/camunda-bpm-platform
# TRY TO GET https://github.com/datakurre/camunda-cockpit-plugins/ working.
# WITH: docker run -d -P camunda-robotframework-demo_camunda
# WORKING OTHER WAYS NOT WORK
#USER root
#RUN set -xe && \
#    apk upgrade --no-cache && \
#    apk add --no-cache \
#        git
#USER camunda
#RUN git clone https://github.com/datakurre/camunda-cockpit-plugins.git /tmp/camunda-cockpit-plugins && \
#    cp -Rfv /tmp/camunda-cockpit-plugins/* /camunda/webapps/camunda/app/cockpit/scripts/.  && \
#    rm -Rf /tmp/camunda-cockpit-plugins
